// REPLACE THIS WITH YOUR CLOUDFLARE WORKER URL
const WORKER_URL = "https://appstore-proxy.4445622.workers.dev";

document.addEventListener('DOMContentLoaded', () => {
    fetchApps();
});

async function fetchApps() {
    const grid = document.getElementById('apps-grid');
    const loading = document.getElementById('loading');

    try {
        // Fetch the apps database generated by GitHub Actions
        const response = await fetch('apps.json');
        if (!response.ok) {
            throw new Error('Failed to load apps data');
        }
        
        const apps = await response.json();
        loading.style.display = 'none';

        if (apps.length === 0) {
            grid.innerHTML = '<div style="grid-column: 1/-1; text-align: center; color: var(--text-secondary);">No apps available yet.</div>';
            return;
        }

        apps.forEach(app => {
            const card = createAppCard(app);
            grid.appendChild(card);
        });

    } catch (error) {
        console.error("Error loading apps:", error);
        loading.textContent = 'Failed to load app store. Please try again later.';
    }
}

function formatBytes(bytes, decimals = 2) {
    if (!+bytes) return '0 Bytes';
    const k = 1024;
    const dm = decimals < 0 ? 0 : decimals;
    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
}

function createAppCard(app) {
    const card = document.createElement('div');
    card.className = 'app-card';

    // Construct image URL using the worker
    let imgHTML = '';
    if (app.icon_id) {
        imgHTML = `<img src="${WORKER_URL}/?id=${app.icon_id}&action=image" alt="${app.name} icon" class="app-icon" loading="lazy" onerror="this.outerHTML='<div class=\\'app-icon fallback\\'>📦</div>'">`;
    } else {
        imgHTML = `<div class="app-icon fallback">📦</div>`;
    }

    const downloadLink = `${WORKER_URL}/?id=${app.file_id}&action=download`;
    const formattedSize = formatBytes(app.size);

    card.innerHTML = `
        <div class="app-header">
            ${imgHTML}
            <div>
                <h3 class="app-title">${app.name}</h3>
                <div class="app-size">${formattedSize}</div>
            </div>
        </div>
        <p class="app-description">${app.description}</p>
        <a href="${downloadLink}" class="download-btn" target="_blank" rel="noopener noreferrer">Download</a>
    `;

    return card;
}
